### ISSUE TITLE
bug of multple same key parameter  throws parameter count dismatch

### ISSUE THREAD

**Issue by aruanruan** [pryzach/midao#1]
when my sql is:

select \* from a where user_id = :id union select \* from b where user_id = :id: 

i passed parameter with Map&lt;String, Object&gt;.put("id", "admin") 

the class QueryParameter only register one position  for name id, actually, maybe multiple positions for same key

the field Map&lt;String, Integer&gt; order   should be Map&lt;String, Set&lt;Integer&gt;&gt; order

**Comment by pryzach** [comment]
Thank you very much for taking time and raising this issue.
I agree with you - sometimes one parameter can be used more than once.

I will update this entry once issue is fixed.

Thank you

**Comment by pryzach** [comment]
Small update:

this feature would be delivered along with v.0.9.5 (second half of September)

**Comment by pryzach** [comment]
As promised - delivered modification in version 0.9.5.
Modification allows using one parameter for different positions, but direction is set per parameter only (not per position).

Please let me know if you are experiencing any issues/limitations with current implementation - I would be happy to assist.

P.S. link to example: https://github.com/pryzach/midao/blob/master/midao-jdbc-examples/src/main/java/org/midao/jdbc/examples/derby/QueryMultipleParameterUsageExample.java

Thank you
